### ISSUE TITLE
Increase database connection timeout

### ISSUE THREAD

**Issue by wceolin** [zoonk/zoonk#197]
We usually run our database on Neon with an auto-suspend feature. This means the database can have a cold start. According to the docs, it's usually around 500ms but Sentry has logged 6 timeout errors in the past 2 months in our demo app, suggesting it's taking much longer than that to start the database.

By default the [Postgres adapter](https://hexdocs.pm/ecto_sql/Ecto.Adapters.Postgres.html#module-connection-options), has a 5 seconds connection timeout. We should probably increase the `:connect_timeout` option to make sure it can handle longer cold starts from the database.

**Comment by vish198910** [comment]
Hi @wceolin,

I've been working professionally with Elixir for about 2.5 years and recently came across the Zoonk project. As a regular Duolingo user, I'm excited about the opportunity to contribute to a project with a similar mission. I'd love to get started with Zoonk, so if possible, could you please assign this issue me to it, quite a small change?

Thanks!

**Comment by vish198910** [comment]
@wceolin Do we have definite limit to how much should we increase the timeout?

**Comment by wceolin** [comment]
Sorry for the delay, @vish198910. I've been sick for the past few days. I think increasing it to 30 seconds should be enough to deal with cold starts.

Thanks for your help, I really appreciate it.

**Comment by vish198910** [comment]
No worries @wceolin , hope you're feeling better now! I'll go ahead and increase it to 30 seconds and test it out. Thanks for the suggestion, and let me know if there's anything else you'd like me to adjust.
